### ISSUE TITLE
Master IR issue

### ISSUE THREAD

**Issue by Mamilla17** [kattaliraees/nrf52-IR#1]
When Iam trying to flash, im getting error as i mentioned in below, please help me in this.

In file included from ../../../main.c:30:
../../../Ir_transmitter.h:21:62: error: unknown type name 'ir_transmit_complete_task'; did you mean 'ir_decode_complete_task'?
   21 | bool send_ir_burst(ir_data_t *ir_data, uint32_t pulse_count, ir_transmit_complete_task t);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                              ir_decode_complete_task
../../../main.c: In function 'ir_decode_task_completed':
../../../main.c:65:5: error: implicit declaration of function 'send_ir_burst' [-Werror=implicit-function-declaration]
   65 |     send_ir_burst(ir_data_ptr, number_of_bits, &ir_transmit_task_completed);
      |     ^~~~~~~~~~~~~
cc1: all warnings being treated as errors
../../../../../../components/toolchain/gcc/Makefile.common:272: recipe for target '_build/nrf52832_xxaa/main.c.o' failed
make: *** [_build/nrf52832_xxaa/main.c.o] Error 1

**Comment by kattaliraees** [comment]
@Mamilla17  Pull the latest code and try
